project:
  type: website
  output-dir: docs

website:
  title: "Student Loan Forgiveness"
  favicon: images/dollar_sign.png
  page-footer:
    center: "Student Loan Forgiveness"
    background: primary
    
  navbar:
    left:
      - href: index.qmd
        text: "Introduction"
      - text: "Data Acquisition"
        menu:
          - text: "NewsAPI"
            href: data_newsapi.qmd
          - text: "Reddit"
            href: data_reddit.qmd
      - text: "Data Vectorization"
        menu:
          - text: "NewsAPI"
            href: vectorization_newsapi.qmd
          - text: "Reddit"
            href: vectorization_reddit.qmd
      - href: clustering.qmd
        text: "Clustering"
      - href: arm.qmd
        text: "Association Rule Mining"
      - href: lda.qmd
        text: "Latent Dirichlet Allocation"
      - text: "Modeling"
        menu:
          - text: "Modeling Preparations"
            href: modeling_prep.qmd
          - text: "Naive Bayes"
            href: modeling_nb.qmd
          - text: "Decision Trees"
            href: modeling_dt.qmd
          - text: "Support Vector Machines Classification"
            href: modeling_svm.qmd
          - text: 'Modeling Conclusions'
            href: modeling_conclusion.qmd
    right:
      - icon: github
        href: https://github.com/Student-Loan-Forgiveness/Student-Loan-Forgiveness

format:
  html:
    email-obfuscation: javascript
    grid:
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
    citations-hover: true
    code-fold: true
    theme: flatly
    css: styles.css
    code-block-border-left: primary
    toc: true
