---
title: "Introduction"
bibliography: references.bib
csl: diabetologia.csl
---

Many were told while growing up, “Go to college and you’ll be set.”
There was a promise that this would guarantee a certain quality of life along with meaningful, lucrative, and stable careers.
The assurance made the venture seem like a solid investment in both time and money and can even make foregoing college altogether nonnegotiable.
However, with the rising cost of higher education, a volatile job market, and current salaries not keeping up with inflation, many who bought into this dream via private and federal loans are having buyer’s remorse.
Especially when interest is accounted for, some are even unable to afford their payments at all or may take longer than initially expected [@opencampusLikeDrowning].
This begs the question, should the U.S. government provide student loan relief?
Although this is a complex issue with many factors, there are generally two core views.
One side argues “yes” or “does support” while the other argues “no” or “doesn’t support”.
The stances are also drawn along political party lines, with the left supporting the idea more than the right.
In fact, one national poll shows 58% of Democrats were in favor of relief, versus just 15% of Republicans [@theweekProsCons].

How are news organizations reporting on this?
What is the general population saying about this?
Given that the dichotomy extends along political lines, are there differences in dialogue between left-leaning and right-leaning entities?
Points from both sides of the topic were laid out by Becca Stanek from the Week in [@theweekProsCons].
Some of the arguments supporting student loan forgiveness were of the cruelty surrounding the structure of student loans, improving economic equity, and that the cost of college and living, even when accounting for inflation, have increased dramatically since the generation before current students and recent graduates.
Some of the arguments against the idea were an unfairness towards those who have paid off their loans, that it doesn’t address the root problem, and that bulk relief may benefit those who actually do not need the financial aid.
Many of those with student loan repayments are overwhelmed by the system and struggling to pursue life goals they thought an education would offer them [@investopediaMostStudent].
These life goals include creating emergency or retirement funds, investing, owning a home, and postponing starting a family. However, many opponents ask the question, “Where does this money come from?”
A number of Republicans say that government sponsored plans could “increase the federal budget and tax costs.”
There’s an echo of unfairness in increasing taxes on those who don’t have student loans or didn’t even attend college.

Is there any common ground between the two sides of the arguments?
What is the “cruelty” in the system that proponents use as an argument?
Similarly, what is the underlying problem in the system that won’t be solved by forgiveness that opponents use an argument?
In an article on NPR, Corey Turner investigates fraudulent colleges. The article claims that for-profit trade schools which serve almost a quarter of federal student loan borrowers account for “44%” of defaults [@nprDefraud].
The author cites examples of Corinthian Colleges, ITT Technical Institute, and DeVry University, whose students have “wasted loans and worthless degrees” and may have been misled by false advertising.
In the case of fraud, there seems to be more bilateral support.
Fraudulent colleges aside, the cost of education is still rising, “having nearly tripled since 1980”, and the back and forth on forgiveness is frustrating to both sides of the discussion [].
Although a single cause of this increase is hard to pinpoint, some are blaming the student aid system and the institutions themselves.
A bulk forgiveness would be costly to taxpayers and even eliminating interest could be damaging.
Instead, a recommendation was made to tighten lending requirements and condition borrowing limits on a “degree’s economic returns” and “borrower’s academic merit.”
